# Generated by Django 5.1.2 on 2026-04-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Meuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quantite_en_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meubles/', verbose_name='Image')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuble.categorie', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meuble.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Meuble',
                'verbose_name_plural': 'Meubles',
                'ordering': ['nom'],
            },
        ),
    ]
